server:
  port: 18092
spring:
  application:
    name: seckill
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/changgou_seckill?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
  rabbitmq:
    host: 129.211.164.41 #mq的服务器地址
    username: user #账号
    password: 123456
    port: 5672 #端口
  main:
    allow-bean-definition-overriding: true
  redis:
    host: 182.92.106.193
    password: VIKCireqXSsbMg5G
    port: 6379
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true
#hystrix 配置
hystrix:
  command:
    default:
      execution:
        timeout:
          #如果enabled设置为false，则请求超时交给ribbon控制
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 400000
          strategy: SEMAPHORE

#    位置支付交换机和队列
mq:
  pay:
    exchange:
      order: exchange.order
      seckillorder: exchange.seckillorder
    queue:
      order: queue.order #普通队列
      seckillorder: queue.seckillorder #秒杀队列 在支付模块中生成
      seckillordertimer: queue.seckillordertimer #延时队列过期转发队列
      seckillordertimerdelay: queue.seckillordertimerdelay  #延时队列1
    routing:
      orderkey: queue.order
      seckillorderkey: queue.seckillorder