server:
  port: 18091
spring:
  application:
    name: pay
  main:
    allow-bean-definition-overriding: true
  rabbitmq:
    host: 129.211.164.41
    port: 5672
    username: user
    password: 123456
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true
#hystrix 配置
hystrix:
  command:
    default:
      execution:
        timeout:
          #如果enabled设置为false，则请求超时交给ribbon控制
          enabled: true
        isolation:
          strategy: SEMAPHORE

#微信支付信息配置
weixin:
  appid: wx8397f8696b538317
  partner: 1473426802
  partnerkey: T6m9iK73b0kn9g5v426MKfHQH7X8rKwb
  notifyurl:  http://3563l0682w.zicp.vip:33540/weixin/pay/notify/url #内网穿透支付回调

#配置连接mq

#配置支付交换机和队列
mq:
  pay:
    exchange:
      order: exchange.order
      #秒杀
      seckillorder: exchange.seckillorder
    queue:
      order: queue.order
      #秒杀
      seckillorder: queue.seckillorder
      seckillordertimer: queue.seckillordertimer
    routing:
      orderkey: queue.order
      #秒杀
      seckillorderkey: queue.seckillorder

